name: Release and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-tags: true
          fetch-depth: 0
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Publish to NPM
        if: ${{ env.NPM_CONFIG_TOKEN != '' }}
        run: bun run publish ${{ env.VERSION }}
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create custom changelog config
        run: |
          echo "module.exports = { types: [ { type: 'feat', section: 'ðŸš€ ÐÐ¾Ð²Ñ‹Ðµ Ð²Ð¾Ð·Ð¼Ð¾Ð¶Ð½Ð¾ÑÑ‚Ð¸' }, { type: 'fix', section: 'ðŸ› Ð˜ÑÐ¿Ñ€Ð°Ð²Ð»ÐµÐ½Ð¸Ñ' }, { type: 'ci', section: 'âš™ï¸ CI/CD' }, { type: 'chore', section: 'ðŸ”§ ÐŸÑ€Ð¾Ñ‡ÐµÐµ' } ] };" > changelog.config.js
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: 'main'
          skip-git-pull: "true"
          skip-bump: "true" 
          skip-commit: "true"
          skip-tag: "true"
          output-file: "false"
          config-file-path: './changelog.config.js'
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
